"""
This module contains the `QEProcessRunner` class.
"""

import logging
import subprocess
from pathlib import Path

from ase.calculators.espresso import EspressoProfile

from mlip_autopipec.exceptions import DFTCalculationError

logger = logging.getLogger(__name__)


class QEProcessRunner:
    """
    Executes a Quantum Espresso calculation in a secure subprocess.

    This class is responsible for running the `pw.x` executable. It constructs
    the command using ASE's `EspressoProfile` and executes it in a sandboxed
    environment, capturing stdout and stderr.
    """

    def __init__(self, profile: EspressoProfile) -> None:
        """
        Initializes the QEProcessRunner.

        Args:
            profile: An ASE `EspressoProfile` configured with the path to the
                     `pw.x` executable.
        """
        self.profile = profile

    def execute(self, input_path: Path, output_path: Path) -> None:
        """
        Runs `pw.x` using the provided input file.

        Args:
            input_path: Path to the `espresso.pwi` input file.
            output_path: Path where the stdout of the `pw.x` run will be
                         written.

        Raises:
            FileNotFoundError: If the `pw.x` executable is not found.
            subprocess.CalledProcessError: If `pw.x` returns a non-zero exit
                                           code.
        """
        command = self.profile.get_command(inputfile=str(input_path))
        try:
            with input_path.open() as stdin_f, output_path.open("w") as stdout_f:
                # SECURITY: The `command` is generated by ASE's EspressoProfile
                # and is not derived from user input, mitigating command
                # injection risks. `shell=False` is explicitly set as a best
                # practice.
                process = subprocess.run(
                    command,
                    shell=False,
                    check=True,
                    capture_output=True,
                    text=True,
                    stdin=stdin_f,
                )
                stdout_f.write(process.stdout)
        except FileNotFoundError as e:
            logger.error(f"QE executable not found. Details: {e}")
            raise
        except subprocess.CalledProcessError as e:
            logger.exception("QE subprocess failed with a non-zero exit code.")
            raise DFTCalculationError(
                "The DFT calculation failed.",
                stdout=e.stdout,
                stderr=e.stderr,
            ) from e
