target_system:
  name: FeNi System
  elements:
  - Fe
  - Ni
  composition:
    Fe: 0.7
    Ni: 0.3
  crystal_structure: fcc
dft:
  command: pw.x
  pseudopotential_dir: /home/tomo/qe_calc/pseudos/
  ecutwfc: 40.0
  kspacing: 0.15
  nspin: 2
runtime:
  database_path: mlip.db
  work_dir: _work
training_config:
  cutoff: 5.0
  b_basis_size: 300
  kappa: 0.5
  kappa_f: 100.0
  max_iter: 100
  batch_size: 32
inference_config:
  lammps_executable: /path/to/lmp
  temperature: 1000.0
  steps: 10000
  uncertainty_threshold: 10.0
workflow:
  max_generations: 5
  workers: 2
