"""
Script Generator Module.

This module provides the ScriptGenerator class for creating LAMMPS input scripts.
"""

from pathlib import Path

from mlip_autopipec.config.schemas.inference import InferenceConfig


class ScriptGenerator:
    def __init__(self, config: InferenceConfig) -> None:
        self.config = config

    def generate(self, atoms_file: Path, potential_path: Path, dump_file: Path) -> str:
        # Determine ensemble fix
        if self.config.ensemble == "nvt":
            tdamp = self.config.timestep * 100
            fix_cmd = (
                f"fix 1 all nvt temp {self.config.temperature} {self.config.temperature} {tdamp}"
            )
        elif self.config.ensemble == "npt":
            tdamp = self.config.timestep * 100
            pdamp = self.config.timestep * 1000
            fix_cmd = f"fix 1 all npt temp {self.config.temperature} {self.config.temperature} {tdamp} iso {self.config.pressure} {self.config.pressure} {pdamp}"
        else:
            msg = f"Unsupported ensemble: {self.config.ensemble}"
            raise ValueError(msg)

        # Construct pair_coeff string dynamically
        # pair_coeff * * potential_path Element1 Element2 ...
        elements_str = " ".join(self.config.elements)
        pair_coeff_cmd = f"pair_coeff * * {potential_path.resolve()} {elements_str}"

        lines = [
            "# LAMMPS input script generated by MLIP-AutoPipe",
            "units metal",
            "atom_style atomic",
            "boundary p p p",
            "box tilt large",
            f"read_data {atoms_file.resolve()}",
            "",
            "# Potential setup",
            "pair_style pace",
            pair_coeff_cmd,
            "",
            "# Settings",
            "neighbor 1.0 bin",
            "neigh_modify delay 0 every 1 check yes",
            f"timestep {self.config.timestep}",
            "",
            "# Compute Gamma (Extrapolation Grade)",
            "compute pace all pace",
            "compute max_gamma all reduce max c_pace[1]",
            "",
            "# Thermo output",
            "thermo_style custom step temp press pe c_max_gamma",
            f"thermo {self.config.sampling_interval}",
            "",
            "# Dump high uncertainty configurations",
            f"dump my_dump all custom {self.config.sampling_interval} {dump_file.resolve()} id type x y z fx fy fz c_pace[1]",
            f"dump_modify my_dump thresh c_max_gamma > {self.config.uq_threshold}",
            "",
            "# Run",
            fix_cmd,
            f"run {self.config.steps}",
            "unfix 1",
        ]

        return "\n".join(lines)
