import logging
import shutil
import subprocess
from pathlib import Path

from ase import Atoms

import mlip_autopipec.inference.pace_driver as driver_module
from mlip_autopipec.config.config_model import EonConfig

logger = logging.getLogger(__name__)


class EonWrapper:
    def __init__(self, config: EonConfig) -> None:
        self.config = config

    def run_akmc(self, structure: Atoms, work_dir: Path, potential_path: Path) -> list[Atoms]:
        """
        Runs EON aKMC/Saddle search starting from the given structure.
        """
        work_dir.mkdir(parents=True, exist_ok=True)

        self._prepare_directory(work_dir, structure, potential_path)

        cmd = [self.config.command]
        logger.info(f"Running EON: {cmd} in {work_dir}")

        candidates = []

        try:
            # We assume eonclient runs a search and exits
            subprocess.run(  # noqa: S603
                cmd,
                cwd=work_dir,
                capture_output=True,
                text=True,
                check=True,
            )

            # If successful, check for products/saddles
            proc_dir = work_dir / "processes"
            if proc_dir.exists():
                for _ in proc_dir.glob("*/saddle.con"):
                    pass

        except subprocess.CalledProcessError as e:
            if e.returncode == 100:
                logger.info("EON halted due to potential uncertainty.")
                # Return the current state or identify the bad configuration
                candidates.append(structure)
            else:
                logger.exception(f"EON failed with code {e.returncode}")

        return candidates

    def _prepare_directory(self, work_dir: Path, structure: Atoms, potential_path: Path) -> None:
        # 1. Write config.ini
        self._write_config(work_dir)

        # 2. Write pos.con
        self._write_pos_con(work_dir / "pos.con", structure)

        # 3. Copy pace_driver.py
        driver_src = Path(driver_module.__file__)
        shutil.copy(driver_src, work_dir / "pace_driver.py")

        # 4. Copy potential file
        shutil.copy(potential_path, work_dir / "potential.yace")

    def _write_config(self, work_dir: Path) -> None:
        config_path = work_dir / "config.ini"
        with config_path.open("w") as f:
            for section, params in self.config.parameters.items():
                f.write(f"[{section}]\n")
                for k, v in params.items():
                    f.write(f"{k} = {v}\n")
                f.write("\n")

    def _write_pos_con(self, filepath: Path, atoms: Atoms) -> None:
        with filepath.open("w") as f:
            f.write("Generated by MLIP-AutoPipeC\n")

            cell = atoms.get_cell()  # type: ignore[no-untyped-call]
            for row in cell:
                f.write(f"{row[0]:.6f} {row[1]:.6f} {row[2]:.6f}\n")

            f.write(f"{len(atoms)}\n")

            masses = atoms.get_masses()
            positions = atoms.get_positions()  # type: ignore[no-untyped-call]
            symbols = atoms.get_chemical_symbols()  # type: ignore[no-untyped-call]

            for i in range(len(atoms)):
                # Type Mass X Y Z Fixed(0) Vx Vy Vz
                m = masses[i] if masses is not None else 1.0
                f.write(f"{symbols[i]} {m:.4f} {positions[i][0]:.6f} {positions[i][1]:.6f} {positions[i][2]:.6f} 0 0.0 0.0 0.0\n")
