import os
from pathlib import Path

from mlip_autopipec.config.base_config import GlobalConfig
from mlip_autopipec.orchestrator.simple_orchestrator import SimpleOrchestrator


def test_full_cycle_mock_execution(temp_config: Path, tmp_path: Path) -> None:
    """
    Runs the full cycle with Mock components.
    This integration test verifies that the Orchestrator orchestrates the Mocks correctly.
    """
    original_cwd = Path.cwd()
    os.chdir(tmp_path)
    try:
        config = GlobalConfig.from_yaml(temp_config)
        orchestrator = SimpleOrchestrator(config)
        orchestrator.run()

        # Verify output directory structure created by the Orchestrator
        # Path now includes project name
        workdir_root = tmp_path / "active_learning" / config.project_name
        assert workdir_root.exists()
        assert (workdir_root / "iter_001").exists()

        # Check for artifacts generated by MockTrainer
        potential_file = workdir_root / "iter_001" / "potential.yace"
        assert potential_file.exists()
        assert potential_file.stat().st_size == 0

        # Check for training report
        report_file = workdir_root / "iter_001" / "training_report.txt"
        assert report_file.exists()
        assert "Training completed successfully" in report_file.read_text()

        # Verify dataset grew
        # Initial: 5 (from MockStructureGenerator default)
        # Iter 1: Compute 5 -> Add 5 -> Train -> Validate (Fail) -> Explore (Halt) -> New 1 (MockDynamics default)
        # Iter 2: Compute 1 -> Add 1 -> Train -> ...
        # Total should be > 5.
        assert len(orchestrator.dataset) > 5

    finally:
        os.chdir(original_cwd)
