import os
from pathlib import Path

from mlip_autopipec.config.base_config import GlobalConfig
from mlip_autopipec.orchestrator.simple_orchestrator import SimpleOrchestrator


def test_full_cycle_mock_execution(temp_config: Path, tmp_path: Path) -> None:
    """
    Runs the full cycle with Mock components.
    This integration test verifies that the Orchestrator orchestrates the Mocks correctly.
    """
    original_cwd = Path.cwd()
    os.chdir(tmp_path)
    try:
        config = GlobalConfig.from_yaml(temp_config)
        orchestrator = SimpleOrchestrator(config)
        orchestrator.run()

        # Verify output directory structure created by the Orchestrator
        active_learning_dir = tmp_path / "active_learning"
        assert active_learning_dir.exists()
        assert (active_learning_dir / "iter_001").exists()

        # Check for artifacts generated by MockTrainer
        potential_file = active_learning_dir / "iter_001" / "potential.yace"
        assert potential_file.exists()
    finally:
        os.chdir(original_cwd)
