"""Master UAT and Tutorial Script for Cycle 06."""

import os
import shutil
import sys
from pathlib import Path

try:
    import marimo
except ImportError:
    marimo = None

import yaml
from loguru import logger

from pyacemaker.core.config_loader import load_config
from pyacemaker.orchestrator import Orchestrator

# Configuration matching strict schema
UAT_CONFIG = {
    "project": {
        "name": "Cycle06_UAT",
        "root_dir": "uat_output",
    },
    "orchestrator": {
        "max_cycles": 1,
        "n_local_candidates": 2,
        "n_active_set_select": 2,
        "dataset_file": "dataset.json",
        "validation_file": "validation.json",
        "validation_split": 0.2,
    },
    "structure_generator": {
        "strategy": "random",
        "parameters": {
            "composition": {"Si": 2},
            "box_size": [5.0, 5.0, 5.0],
            "n_initial": 5,
        }
    },
    "oracle": {
        "mock": False,
        "dft": {
            "pseudopotentials": {"Si": "Si.pbe-n-kjpaw_psl.1.0.0.UPF"},
        },
        "mace": {
            "model_path": "medium",
        }
    },
    "trainer": {
        "potential_type": "ace",
        "parameters": {
            "loss": {"kappa": 0.5},
        }
    },
    "validator": {
        "phonon_supercell": [2, 2, 2],
        "phonon_tolerance": -0.05,
        "eos_strain": 0.05,
        "eos_points": 5,
        "elastic_strain": 0.01,
    },
    "dynamics_engine": {
        "engine": "ase",
    },
    "distillation": {
        "enable_mace_distillation": False
    }
}

# Check for Mock Mode via Environment Variable (Standard in CI)
IS_MOCK = os.environ.get("MOCK_MODE", "false").lower() == "true"
if IS_MOCK:
    logger.info("Running in Mock Mode")
    UAT_CONFIG["orchestrator"]["max_cycles"] = 1
    UAT_CONFIG["structure_generator"]["parameters"]["n_initial"] = 2
    UAT_CONFIG["oracle"]["mock"] = True
    UAT_CONFIG["trainer"]["mock"] = True


def main() -> None:
    """Main execution function."""
    logger.info("Starting UAT Script...")

    # 1. Setup Environment
    # Use relative path for output
    output_dir = Path(UAT_CONFIG["project"]["root_dir"]).absolute()  # type: ignore[arg-type]
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Ensure data directory exists (Orchestrator expects it)
    data_dir = output_dir / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    # Create dummy UPF file to pass validation
    upf_name = UAT_CONFIG["oracle"]["dft"]["pseudopotentials"]["Si"]
    upf_path = output_dir / upf_name
    upf_path.touch()
    # Update config to use absolute path
    UAT_CONFIG["oracle"]["dft"]["pseudopotentials"]["Si"] = str(upf_path)

    # Save config
    config_path = output_dir / "config.yaml"
    with config_path.open("w") as f:
        yaml.dump(UAT_CONFIG, f)

    # 2. Load Config
    try:
        config = load_config(config_path)
    except Exception as e:
        logger.error(f"Failed to load config: {e}")
        raise

    # 3. Run Orchestrator
    orchestrator = Orchestrator(config, base_dir=output_dir)
    result = orchestrator.run()

    if result.status == "failed":
        logger.error(f"Orchestrator failed: {result.error}")
        sys.exit(1)

    # 4. Verify Outputs
    validation_report = output_dir / "validation" / "validation_report.html"
    if validation_report.exists():
        logger.info(f"Validation report generated at {validation_report}")
        logger.info("Validation complete.")
    else:
        logger.error("Validation report missing!")
        # If in Mock mode, report should be generated by MockValidator (which we updated)
        sys.exit(1)

    logger.info("UAT Completed Successfully.")


if __name__ == "__main__":
    main()
