DEFAULT_CONFIG_FILENAME = "config.yaml"
DEFAULT_LOG_FILENAME = "mlip_pipeline.log"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_PROJECT_NAME = "MyMLIPProject"
DEFAULT_ELEMENTS = ["Ti", "O"]
DEFAULT_CUTOFF = 5.0
DEFAULT_SEED = 42

# ACE Defaults
DEFAULT_ACE_NPOT = "FinnisSinclair"
DEFAULT_ACE_FS_PARAMS = [1.0, 1.0, 1.0, 0.5]
DEFAULT_ACE_NDENSITY = 2

# Structure Defaults (Bulk)
DEFAULT_STRUCT_STRATEGY = "bulk"
DEFAULT_STRUCT_ELEMENT = "Si"
DEFAULT_STRUCT_CRYSTAL = "diamond"
DEFAULT_STRUCT_LATTICE = 5.43
DEFAULT_STRUCT_RATTLE = 0.1
DEFAULT_STRUCT_SUPERCELL = (1, 1, 1)

# MD Defaults
DEFAULT_MD_TEMP = 300.0
DEFAULT_MD_STEPS = 1000
DEFAULT_MD_TIMESTEP = 0.001
DEFAULT_MD_ENSEMBLE = "NVT"
