# Default exploration parameters
DEFAULT_TEMPERATURE_SCHEDULE = [300.0, 600.0, 1200.0]
DEFAULT_MD_STEPS = 1000
DEFAULT_MC_SWAP_PROB = 0.1
DEFAULT_DEFECT_DENSITY = 0.0
DEFAULT_STRAIN_RANGE = 0.05
DEFAULT_LOCAL_CANDIDATES = 20
DEFAULT_LOCAL_SAMPLING_METHOD = "perturbation"

# Default Generator parameters
DEFAULT_RATIO_AB_INITIO = 0.1
DEFAULT_MOCK_COUNT = 2

# Default Oracle parameters
DEFAULT_KSPACING = 0.04
DEFAULT_ENCUT = 60.0
DEFAULT_MIXING_BETA = 0.7
DEFAULT_SMEARING_WIDTH = 0.01
DEFAULT_SYMMETRY_PRECISION = 1e-5
DEFAULT_N_WORKERS = 1

# Default Trainer parameters
DEFAULT_MAX_EPOCHS = 100
DEFAULT_BATCH_SIZE = 32
DEFAULT_SELECTION_RATIO = 0.1
DEFAULT_N_ACTIVE_SET = 5

# Default Dynamics parameters
DEFAULT_DYNAMICS_TEMP = 300.0
DEFAULT_DYNAMICS_STEPS = 1000
DEFAULT_MOCK_FRAMES = 5
DEFAULT_MAX_GAMMA = 5.0

# Default Validator parameters
DEFAULT_ELASTIC_TOLERANCE = 0.15

# Default Orchestrator parameters
DEFAULT_MAX_CYCLES = 1
DEFAULT_MAX_CANDIDATES = 50

# Default System parameters
DEFAULT_MAX_VACUUM = 50.0
DEFAULT_HEALER_MIXING_BETA = 0.3
DEFAULT_HEALER_DEGAUSS = 0.02
DEFAULT_BUFFER_SIZE = 1000
DEFAULT_EON_TIME_STEP = 1.0
DEFAULT_LOG_FILE = "mlip_pipeline.log"

# Mock Content
MOCK_POTENTIAL_CONTENT = "MOCK POTENTIAL FILE CONTENT"
