from typing import List, Tuple

# General
DEFAULT_LOG_FILENAME = "mlip_pipeline.log"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_PROJECT_NAME = "MyMLIPProject"

# Potential
DEFAULT_ELEMENTS: List[str] = []
DEFAULT_CUTOFF = 5.0
DEFAULT_SEED = 42
DEFAULT_LAMMPS_COMMAND = "lmp"
DEFAULT_PAIR_STYLE = "hybrid/overlay"
DEFAULT_ZBL_INNER = 1.0
DEFAULT_ZBL_OUTER = 2.0

# ACE
DEFAULT_ACE_NPOT = "FinnisSinclair"
DEFAULT_ACE_FS_PARAMS = [1.0, 1.0, 1.0, 0.5]
DEFAULT_ACE_NDENSITY = 2

# Pacemaker Fitting
DEFAULT_PACEMAKER_DELTA_SPLINE_BINS = 0.001
DEFAULT_PACEMAKER_LOSS_WEIGHT_ENERGY = 1.0
DEFAULT_PACEMAKER_LOSS_WEIGHT_FORCES = 1.0
DEFAULT_PACEMAKER_LOSS_WEIGHT_STRESS = 0.1

# Orchestrator
DEFAULT_MAX_ITERATIONS = 1
DEFAULT_UNCERTAINTY_THRESHOLD = 5.0
DEFAULT_HALT_THRESHOLD = 5
DEFAULT_VALIDATION_FREQUENCY = 1
DEFAULT_TRAJECTORY_STRIDE = 1
DEFAULT_DFT_BATCH_SIZE = 10
DEFAULT_DATA_DIR = "data"

# File Names
DEFAULT_TRAJ_FILE_LAMMPS = "dump.lammpstrj"
DEFAULT_TRAJ_FILE_EXTXYZ = "dump.extxyz"
DEFAULT_LOG_FILE_LAMMPS = "log.lammps"
DEFAULT_INPUT_FILE_LAMMPS = "in.lammps"
DEFAULT_DATA_FILE_LAMMPS = "data.lammps"
DEFAULT_STDOUT_FILE = "stdout.log"
DEFAULT_STDERR_FILE = "stderr.log"
DEFAULT_ALLOWED_COMMAND_PREFIXES = ["lmp", "lammps", "mpirun", "srun"]

# Structure Gen (Bulk)
DEFAULT_BULK_STRATEGY = "bulk"
DEFAULT_BULK_ELEMENT = "Si"
DEFAULT_BULK_CRYSTAL = "diamond"
DEFAULT_BULK_LATTICE = 5.43
DEFAULT_BULK_RATTLE = 0.0
DEFAULT_BULK_SUPERCELL: Tuple[int, int, int] = (1, 1, 1)

# MD
DEFAULT_MD_TEMP = 300.0
DEFAULT_MD_STEPS = 1000
DEFAULT_MD_TIMESTEP = 0.001
DEFAULT_MD_ENSEMBLE = "NVT"

# Validation
DEFAULT_PHONON_TOL = -0.05
DEFAULT_PHONON_SUPERCELL: Tuple[int, int, int] = (2, 2, 2)
DEFAULT_ELASTIC_TOL = 1e-4
DEFAULT_EOS_RANGE = 0.1
DEFAULT_EOS_POINTS = 10
DEFAULT_REPORT_PATH = "validation_report.html"
DEFAULT_VAL_RATTLE = 0.0

# Training
DEFAULT_TRAIN_BATCH = 100
DEFAULT_TRAIN_EPOCHS = 100
DEFAULT_TRAIN_LADDER = [100, 10]
DEFAULT_TRAIN_KAPPA = 0.4
DEFAULT_ACTIVE_SET_OPT = True
DEFAULT_MAX_ACTIVE_SET = 1000
DEFAULT_TRAIN_WORK_DIR = "training_work"

# Production
DEFAULT_PACKAGE_NAME_FORMAT_FALLBACK = "mlip_package_{version}.zip"
